# Path to female DNAseq reads 
female_reads: '/fs/cbsufsrv5/data1/ya76/DNAseq/Y.chrom/Dvir_female.fastq.gz'

# Path to male DNAseq reads (optional)
male_reads: '/fs/cbsufsrv5/data1/ya76/DNAseq/Y.chrom/Dvir_male.fastq.gz'

# Path to PacBio genome assembly
genome: '/home/ya76/Platinum_Genomes/GENOMES/D.virilis/DvirPacBio_ME_repMasked_jb.fa'

# set output dir
OUT_DIR: '/fs/cbsubscb14/storage/ya76/Snakemake.Output.Folders/YGS.PacBio.Dvir_repMasked_JB'
WORK_DIR: '/workdir'
